def resume():
    a=input("Enter your name:")
    b=input("Enter your date of birth:")
    c=input("Enter your age:")
    d=input("Father name:")
    e=input("Contact number:")
    f=input("E-mail:")
    g=input("Address:")
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
resume()
resume()
resume()
resume()
resume()
resume()
resume()
resume()
resume()
resume()
